<?php

/**
 * MIT License
 *
 * Copyright (c) 2018 Samuel CHEMLA
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

namespace PhpBg\DvbPsi\Descriptors;

use MyCLabs\Enum\Enum;

/**
 * Class Descriptor
 * @see Final draft ETSI EN 300 468 V1.13.1 (2012-04), 6 Descriptors
 */
class Identifier extends Enum
{
    const NETWORK_NAME_DESCRIPTOR = 0x40;
    const SERVICE_LIST_DESCRIPTOR = 0x41;
    const STUFFING_DESCRIPTOR = 0x42;
    const SATELLITE_DELIVERY_SYSTEM_DESCRIPTOR = 0x43;
    const CABLE_DELIVERY_SYSTEM_DESCRIPTOR = 0x44;
    const BOUQUET_NAME_DESCRIPTOR = 0x47;
    const SERVICE_DESCRIPTOR = 0x48;
    const COUNTRY_AVAILABILITY_DESCRIPTOR = 0x49;
    const LINKAGE_DESCRIPTOR = 0x4a;
    const NVOD_REFERENCE_DESCRIPTOR = 0x4B;
    const TIME_SHIFTED_SERVICE_DESCRIPTOR = 0x4C;
    const SHORT_EVENT_DESCRIPTOR = 0x4d;
    const EXTENDED_EVENT_DESCRIPTOR = 0x4e;
    const TIME_SHIFTED_EVENT_DESCRIPTOR = 0x4f;
    const COMPONENT_DESCRIPTOR = 0x50;
    const MOSAIC_DESCRIPTOR = 0x51;
    const STREAM_IDENTIFIER_DESCRIPTOR = 0x52;
    const CA_IDENTIFIER_DESCRIPTOR = 0x53;
    const CONTENT_DESCRIPTOR = 0x54;
    const PARENTAL_RATING_DESCRIPTOR = 0x55;
    const TELETEXT_DESCRIPTOR = 0x56;
    const TELEPHONE_DESCRIPTOR = 0x57;
    const LOCAL_TIME_OFFSET_DESCRIPTOR = 0x58;
    const SUBTITLING_DESCRIPTOR = 0x59;
    const TERRESTRIAL_DELIVERY_SYSTEM_DESCRIPTOR = 0x5a;
    const MULTILINGUAL_NETWORK_NAME_DESCRIPTOR = 0x5B;
    const MULTILINGUAL_BOUQUET_NAME_DESCRIPTOR = 0x5C;
    const MULTILINGUAL_SERVICE_NAME_DESCRIPTOR = 0x5D;
    const MULTILINGUAL_COMPONENT_DESCRIPTOR = 0x5e;
    const PRIVATE_DATA_SPECIFIER_DESCRIPTOR = 0x5f;
    const SERVICE_MOVE_DESCRIPTOR = 0x60;
    const SHORT_SMOOTHING_BUFFER_DESCRIPTOR = 0x61;
    const FREQUENCY_LIST_DESCRIPTOR = 0x62;
    const PARTIAL_TRANSPORT_STREAM_DESCRIPTOR = 0x63;
    const DATA_BROADCAST_DESCRIPTOR = 0x64;
    const CA_SYSTEM_DESCRIPTOR = 0x65;
    const DATA_BROADCAST_ID_DESCRIPTOR = 0x66;
    const TRANSPORT_STREAM_DESCRIPTOR = 0x67;
    const DSNG_DESCRIPTOR = 0x68;
    const PDC_DESCRIPTOR = 0x69;
    const AC3_DESCRIPTOR = 0x6A;
    const ANCILLARY_DATA_DESCRIPTOR = 0x6B;
    const CELL_LIST_DESCRIPTOR = 0x6C;
    const CELL_FREQUENCY_LINK_DESCRIPTOR = 0x6D;
    const ANNOUNCEMENT_SUPPORT_DESCRIPTOR = 0x6E;
    const APPLICATION_SIGNALLING_DESCRIPTOR = 0x6F;
    const ADAPTATION_FIELD_DATA_DESCRIPTOR = 0x70;
    const SERVICE_IDENTIFIER_DESCRIPTOR = 0x71;
    const SERVICE_AVAILABILITY_DESCRIPTOR = 0x72;
    const DEFAULT_AUTHORITY_DESCRIPTOR = 0x73;
    const RELATED_CONTENT_DESCRIPTOR = 0x74;
    const TVA_ID_DESCRIPTOR = 0x75;
    const CONTENT_IDENTIFIER_DESCRIPTOR = 0x76;
    const TIME_SLICE_FEC_IDENTIFIER_DESCRIPTOR = 0x77;
    const ECM_REPETITION_RATE_DESCRIPTOR = 0x78;
    const S2_SATELLITE_DELIVERY_SYSTEM_DESCRIPTOR = 0x79;
    const ENHANCED_AC3_DESCRIPTOR = 0x7A;
    const DTS_DESCRIPTOR = 0x7B;
    const AAC_DESCRIPTOR = 0x7C;
    const XAIT_LOCATION_DESCRIPTOR = 0x7d;
    const FTA_CONTENT_MANAGEMENT_DESCRIPTOR = 0x7e;
    const EXTENSION_DESCRIPTOR = 0x7f;
}